### ISSUE TITLE
Unifying efforts with ansible-thelounge

### ISSUE THREAD

**Issue by astorije** [cloudnull/Ansible-Playbook-TheLounge#2]
Hi there!

@astorije here, maintainer of The Lounge 🙂

I found your repo by accident while updating one of mines for v3.0.0 that we released today: https://github.com/astorije/ansible-thelounge

Do you still use your repo?
- If yes, would you be interested in joining efforts?
- If no, would you be open to archive your repo (in the GitHub settings) and pointing to mine in your README?

Alternatively, you could link to [our new install guide](https://thelounge.chat/docs/install-and-upgrade).

**Comment by cloudnull** [comment]
I would be happy to contribute to your repo and archive this one. I do still use it but am happy to work collaboratively on a community focused one.
